#!/bin/bash
# Automated Image Migration Script
# Generated by AUTOMATED_PLACEMENT.js

echo "🚀 Starting automated image migration..."

# Create target directories
mkdir -p public/images/{venue,bridal-suite,reception,historical}
mkdir -p public/wedding-photos
mkdir -p public/real-wedding-blogs

# CRITICAL FILES FIRST (CSS/Sanity dependencies)
echo "🚨 Migrating critical venue images..."
cp "migration/venue/barn-exterior-deck-swing-golden-hour.jpg" "public/images/venue/barn-exterior-deck-swing-golden-hour.jpg"
cp "migration/venue/barn-exterior-entrance-lighting-view.jpg" "public/images/venue/barn-exterior-entrance-lighting-view.jpg"
cp "migration/venue/barn-exterior-full-deck-view-evening.jpg" "public/images/venue/barn-exterior-full-deck-view-evening.jpg"
cp "migration/venue/barn-interior-ceiling-beams-lighting.jpg" "public/images/venue/barn-interior-ceiling-beams-lighting.jpg"
cp "migration/venue/barn-interior-exposed-beams-chandeliers.jpg" "public/images/venue/barn-interior-exposed-beams-chandeliers.jpg"
cp "migration/venue/details-swing-rustic-romance.jpg" "public/images/venue/details-swing-rustic-romance.jpg"
cp "migration/venue/property-vineyard-rows-landscape.jpg" "public/images/venue/property-vineyard-rows-landscape.jpg"

# HIGH PRIORITY - Active wedding photos
echo "⚡ Migrating high priority wedding photos..."
cp "migration/weddings/by-couple/anthony-and-linnea/001.jpg" "public/wedding-photos/anthony-and-linnea/001.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/002.jpg" "public/wedding-photos/anthony-and-linnea/002.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/003.jpg" "public/wedding-photos/anthony-and-linnea/003.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/004.jpg" "public/wedding-photos/anthony-and-linnea/004.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/005.jpg" "public/wedding-photos/anthony-and-linnea/005.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/006.jpg" "public/wedding-photos/anthony-and-linnea/006.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/007.jpg" "public/wedding-photos/anthony-and-linnea/007.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/008.jpg" "public/wedding-photos/anthony-and-linnea/008.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/009.jpg" "public/wedding-photos/anthony-and-linnea/009.jpg"
cp "migration/weddings/by-couple/anthony-and-linnea/010.jpg" "public/wedding-photos/anthony-and-linnea/010.jpg"

# VENUE IMAGES
echo "🏛️ Migrating venue images..."
cp -r migration/venue/* public/images/venue/

echo "✅ Critical migration complete!"
echo "🔍 Run validation tests before proceeding with medium priority files."
