import './globals.css';
import '@/styles/hotfix/design-tokens.css';
import '@/styles/hotfix/animations.css';
import '@/styles/hotfix/navbar-styles.css';
import '@/styles/hotfix/hero-styles.css';
import '@/styles/hotfix/alternating-blocks-styles.css';
import '@/styles/hotfix/love-stories-gallery-styles.css';
import '@/styles/hotfix/brand-social-proof-styles.css';
import '@/styles/hotfix/testimonials-styles.css';
import '@/styles/hotfix/history-carousel-styles.css';
import '@/styles/hotfix/schedule-form-styles.css';
import '@/styles/hotfix/map-section-styles.css';
import '@/styles/hotfix/footer-styles.css';
import StoryblokProvider from '@/components/StoryblokProvider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

/*
 * DEV SERVER: http://localhost:6666
 * HOTFIX COMPONENTS: Available at /beta route
 * - NavbarHotfix + HeroHotfix with romantic wedding theme
 * - Pixel-perfect fidelity to original design
 */

export default function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();
	return (
		<StoryblokProvider>
			<html lang="en">
				<head>
					<link rel="preconnect" href="https://fonts.googleapis.com" />
					<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
					<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
				</head>
				<body>
					{children}
				</body>
			</html>
		</StoryblokProvider>
	);
}
